items = Item.create!([
	{ sku: 4044784, name: "Frost Fair Pavilion", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 95.00 },
	{ sku: 4044814, name: "Frost Fair Skaters", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 32.50 },
	{ sku: 4044805, name: "Frost Fair Sled & Ride", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 90.00 },
	{ sku: 4044788, name: "Sledding at the Fair", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 32.50 },
	{ sku: 4036522, name: "Holiday Adventure", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 27.50 },
	{ sku: 4044820, name: "Dickens' Town Tree", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 59.00 },
	{ sku: 4030362, name: "Balmoral Lodge", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 85.00 },
	{ sku: 4036521, name: "Dickens' Carriage Ride", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 49.00 },
	{ sku: 4030361, name: "Camden Coffee House", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 80.00 },
	{ sku: 4025255, name: "Brandon Mill", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 95.00 },
	{ sku: 808905,  name: "Relaxing in Regent's Park", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 25.00 },
	{ sku: 58571,   name: "The Coffee-Stall", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 42.50 },
	{ sku: 58560,   name: "London Newspaper Stand", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 35.00 },
	{ sku: 4044809, name: "Essex Road Fencing Academy", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 100.00 },
	{ sku: 4044818, name: "Touché", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 32.50 },
	{ sku: 4020183, name: "Joseph Edward Tea Shoppe", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 75.00 },
	{ sku: 4020194, name: "Chelsea Market Tea Monger", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 30.00 },
	{ sku: 4044802, name: "London Town Crier", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 20.00 },
	{ sku: 4030360, name: "Six Jolly Fellowship Porters", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 85.00 },
	{ sku: 4030368, name: "A Jolly Good Tune", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 27.50 },
	{ sku: 4044808, name: "The Sword & Shield", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 90.00 },
	{ sku: 4044817, name: "An Evening Stroll", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 26.50 },
	{ sku: 4036510, name: "Straw Duck Pub", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 85.00 },
	{ sku: 4036518, name: "Making Ready for a Full House", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 25.00 },
	{ sku: 58746,   name: "London Gin Distillery", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 100.00 },
	{ sku: 58421,   name: "Red Lion Pub Beer Wagon", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 47.50 },
	{ sku: 58725,   name: "E Tipler Agent Wine Spirits", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 65.00 },
	{ sku: 4020192, name: "Pub Patrons", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 20.00 },
	{ sku: 4043909, name: "The Dower House", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 110.00 },
	{ sku: 4044802, name: "Dowager Countess and Young Friend", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 25.00 },
	{ sku: 4043910, name: "Lord Grantham's Limousine", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 35.00 },
	{ sku: 4044801, name: "Crawley House", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 100.00 },
	{ sku: 4044803, name: "Lady Crawley and Gentleman Friend", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 25.00 },
	{ sku: 4036514, name: "The Downton Legacy Continues", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 27.50 },
  { sku: 4036563, name: "Harley Racing Headquarters", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 115.00 },
  { sku: 4036573, name: "Harley-Davidson Race Ready", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 32.50 },
  { sku: 4036574, name: "Harley-Davidson Top Speed!", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 32.50 },
  { sku: 4035928, name: "Dreaming of a Harley Holiday", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 45.00 },
  { sku: 4035583, name: "Keeper of the Flame", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 25.00 },
  { sku: 4035584, name: "Wild Pair", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 37.50 },
  { sku: 4035585, name: "A Harley Legend", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 17.50 },
  { sku: 4030745, name: "Harley Campfire", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 37.50 },
  { sku: 4030746, name: "Harley Ever After", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 35.00 },
  { sku: 4025316, name: "Harley Road House Café", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 115.00 },
  { sku: 4020216, name: "Harley-Davidson Snow Village", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 110.00 },
  { sku: 4028708, name: "Santa's New Sleigh is a Harley", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 37.50 },
  { sku: 4025324, name: "Hog Heaven", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 35.00 },
  { sku: 4025325, name: "Always a Fun Time on a Harley", description: "A lovely thing", 
		verbose_description: "This is a nice thing to put on your fireplace mantle. All of your friends will be impressed.",
		cost_price: 40.00, vendor: 1151, price: 35.00 }
])

# image = Product.sku(.jpg)
# 1. Dickens' Village
# 2. Downton Abbey
# 3. Harley-Davidson